### ISSUE TITLE
Remove MemoryLeak

### ISSUE THREAD

**Issue by JTheiller** [viniciussanchez/xml-reader#2]
Memory leak identified in TXmlReader due to use of generic list collection added in ParseNode needs to be cleaned
![image](https://github.com/viniciussanchez/xml-reader/assets/7632598/860ab456-e02c-416f-9455-81e956799acb)

**Comment by JTheiller** [comment]
Fix: https://github.com/viniciussanchez/xml-reader/pull/3

**Comment by viniciussanchez** [comment]
Thanks
